### ISSUE TITLE
/usr/bin/rpizero-gcc -- broken

### ISSUE THREAD

**Issue by l0l0l0** [HesselM/rpicross_notes#11]
hello, I try to make your example work, but impossible: - /

I did it again 3x but I always have the same error:

pi@pi-virtual-machine:~/rpi/build/hello/pi$

 ./make
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/rpizero-gcc
-- Check for working C compiler: /usr/bin/rpizero-gcc -- broken
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/usr/bin/rpizero-gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/pi/rpi/build/hello/pi/CMakeFiles/CMakeTmp

    Run Build Command:"/home/pi/rpi/rootfs/usr/bin/make" "cmTC_cbaa5/fast"
    /home/pi/rpi/rootfs/usr/bin/make: 1: /home/pi/rpi/rootfs/usr/bin/make: Syntax error: word unexpected (expecting ")")

I do not understand what I'm doing wrong ... an idea?
thansk

**Comment by l0l0l0** [comment]
sorry it's my fault, I used the last stretch
and that does not work with

**Comment by compyl118** [comment]
Hello, I have the same issue but I do not understand how you solved yours.
Could you give details please?
