### ISSUE TITLE
Could not get past "# Test Setup" in "04-xc-setup.md", Have a solution. 

### ISSUE THREAD

**Issue by Skammi** [HesselM/rpicross_notes#14]
Hi,
I used your guide to setup a cross-compile environment.
I'm using ubuntu 18 and Ros melodic.

First of al I have it running now.

My observations:
1) I used in first instance ~ for /home/pi in the "rpi-generic-toolchain.cmake" file, as my home directory is named differently. I thought that would be more generic. Well it doesn't work, you might want to make that explicit in your documentation. I ended up just changing the pi reverence to fit my home directory.
2) I Got in the same issue as some other people that the running the command:
`cmake -D CMAKE_TOOLCHAIN_FILE=~/rpicross_notes/rpi-generic-toolchain.cmake ~/rpicross_notes/hello/pi`
would evoke the RPI make program. I think that is due to the statements:
`set( RPI_ROOTFS /home/pi/rpi/rootfs )`
`set( CMAKE_FIND_ROOT_PATH ${RPI_ROOTFS} )`
in the "rpi-generic-toolchain.cmake" file. I solved this by adding:
`set( CMAKE_MAKE_PROGRAM "/usr/bin/make"           CACHE FILEPATH "")`
in the "rpi-generic-toolchain.cmake" file.
3) with respect to broken links in your script are 4 files, there are however much more broken links in the "usr/lib/arm-linux-gnueabihf" directory. Are those not relevant or is your shell script just an example? I personally changed the links on the RPI to relative links. That might bite me when I update the RPI, but we will see then.

Moreover, some of the links in the MD files on the web point to no longer existing files.

Thanks
Jacob

**Comment by HesselM** [comment]
Hi Jacob, thanks for the suggestions! 

It was still on my list to fix the precise steps of the wrong invocation. I've updated the guide accordingly. I've also added a notion on the home dir. 

I've also fixed a lot of references. Thought they where ok, turned it wasn't even close. Oops!

If you spot any other mistake or have suggestions to make the steps more clear, or improve, feel free to do a PR or add another comment!
