### ISSUE TITLE
Changes to 01-setup.md

### ISSUE THREAD

**Issue by compyl118** [HesselM/rpicross_notes#15]
Hi, thanks for sharing your tips!
There is something bothering me in the "01-setup.md" section about the "SSH key" part:

 Isn't step 2 supposed to be done in the host ? Because so far the guest system doesn't know anything about xcs_server_rsa.pub.
`XCS~$ chmod 700 xcs_server_rsa xcs_server_rsa.pub`

Since I do have a Windows based host I am using putty and puttygen for theses steps.
I'am not sure if what I made will work with the rest of your notes (still a lot more to read) but if it works, would you like me to write down something about Putty for windows users for you to append to this .md? 
This question would also apply to the DNS part.

**Comment by HesselM** [comment]
Regarding the chmod, yes you are right. A small copy/paste error which has been fixed.

Regarding the DNS, which part do you mean? Turning on the natresolver? That part needs to run on the host.

**Comment by HesselM** [comment]
For putty: if you can test this on windows and write some additional comments on this, that would be awesome. I'm just in the process of (re)building a VM with recent ubuntu and Raspbian to get some project on going (with OSX as host). During this process I might rewrite some parts of the notes, but I'll probably not test all of it. 

For the DNS I'm running into the issue that the XCS cannot ssh the RPI when connecting by hostname. Previously the trick with turning on the natresolver fixed this, but I guess Ubuntu 18 does some things differently. So if you figured this out on windows, I'll be glad to hear about it and append it! (and try if it also works for me)

**Comment by compyl118** [comment]
> Regarding the DNS, which part do you mean? Turning on the natresolver? That part needs to run on the host.

> 

Yes. I think I found how to do it in the windows console using VBoxManage.exe. I'll continue following your notes and I'll keep you informed if it works.

**Comment by HesselM** [comment]
fixed chmod setting in guide
