### ISSUE TITLE
SSH over USB

### ISSUE THREAD

**Issue by compyl118** [HesselM/rpicross_notes#17]
Hello,

I have tried to enable SSH over usb and it works well but I would like to point out that when enabled it messes up with the rest of the network config you propose (at least with DHCP, I have not tried static).

When USB is disconnected but both interfaces (usb0 and wlan0) are declared in "/etc/network/interface", DHCP works well and the pi can connect to the wifi and I can SSH to it.
The weird part is that whenever I try to "apt-get install" something I get a "no route to host error". The weirdest part is that I can ping websites such as google.com but when I ping the websites with the "no route to host error" it doesn't work.

I noticed that when the ping fails the source IP is coming from the USB interface instead of wlan0. So I commented out the usb0 part in "/etc/network/interface" and it "solved" the problem.

Unfortunately I know not enough on the subject to be of much help and I just wanted to point it out in case this is a real issue (and not me doing something wrong).

Cheers

**Comment by HesselM** [comment]
Did you use "old" guide in which you needed to set some settings in "/etc/network/interface"? There was indeed a fault in those settings: the system used "arp" to detect if a interface is up and running and configure the ip adres properly. The idea was to switch between wlan0 or usb0 automatically, however, a static config ALWAYS succeeds as no router is needed to configure the settings. As such, the system never switched as I intended. 

If you used the updated steps, could you post a dump of "/etc/dhcpcd.conf" in the rpi and "ifconfig" ?

**Comment by compyl118** [comment]
I followed the new guide. But after the problem occured I meddled with it a lot.

The output you asked for are in this file : 
[output.txt.txt](https://github.com/HesselM/rpicross_notes/files/4474609/output.txt.txt)

As I said I erased the usb part in dhcpcd.conf and commented the usb part in /etc/network/interface on purpose to make it work again.

**Comment by HesselM** [comment]
Thanks for the output. I'm also interested in how you exactly defined the files when you encountered the issue. I guess the output is of the working setup?

**Comment by compyl118** [comment]
Yes it is. I followed your guide entirely. unfortunately I have no backup of that...

**Comment by HesselM** [comment]
hm too bad. I updated the guide with an example of a setup which works for me. As I cannot verify the troubles you had, and because you fixed the issue in differently, I'll close this issue for know. If someone encounters the same challenges: feel free to reopen the issue with a description of the setup.
